---
apiVersion: v1
kind: Pod
metadata:
  name: app-secrets-env
spec:
  containers:
  - name: mycont
    image: redis
    env:
    - name: SECRET_USER
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret1
          key: password
  restartPolicy: Never
