---
apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
      name: http
    resources:
      limits:
        cpu: "100"
        memory: 256Mi
      requests:
        cpu: "100m"
        memory: 128Mi
