---
apiVersion: v1
kind: Deployment
metadata:
  name: app-livenessprob
  namespace: dendemo
spec:
  containers:
   - name: app
     image: gcr.io/k8s-k3s-405517/dendemo:v1.0.0
     ports:
       - containerPort: 8080
         name: http
     livenessProbe:
       httpGet:
         path: /
         port: 8080
       initialDelaySeconds: 10
       periodSeconds: 15
       timeoutSeconds: 5
       successThreshold: 1
       failureThreshold: 3
