---
apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprobe
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s-405517/dendemo:v2.0.0
    ports:
    - containerPort: 8080
      name: http
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
